name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { mc: 1.21.5, java: 21, fabric: 0.128.2+1.21.5, mappings: 1.21.5+build.1 }
          - { mc: 1.21.6, java: 21, fabric: 0.128.2+1.21.6, mappings: 1.21.6+build.1 }
          - { mc: 1.21.7, java: 21, fabric: 0.129.0+1.21.7, mappings: 1.21.7+build.8 }
          - { mc: 1.21.8, java: 21, fabric: 0.136.0+1.21.8, mappings: 1.21.8+build.1 }
          - { mc: 1.21.9, java: 21, fabric: 0.134.0+1.21.9, mappings: 1.21.9+build.1 }
          - { mc: 1.21.10, java: 21, fabric: 0.138.3+1.21.10, mappings: 1.21.10+build.2 }
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Update gradle.properties
        run: |
          # Minecraft-Version
          sed -i "s/^minecraft_version=.*/minecraft_version=${{ matrix.mc }}/" gradle.properties

          # Yarn Mappings Version
          sed -i "s/^yarn_mappings=.*/yarn_mappings=${{ matrix.mappings }}/" gradle.properties
          
          # Fabric api Version
          sed -i "s/^fabric_version=.*/fabric_version=${{ matrix.fabric }}/" gradle.properties

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build --warning-mode all
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/